name: Bob the Builder

on:
  push:
    branches:
      - '*'

env:
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
  MAKEFLAGS: -j3

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          sudo apt-get install -y build-essential autoconf automake clang tree doxygen
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=/usr CC=${{ matrix.compiler }}
      - name: Build
        run: |
          make V=1
          make install-strip DESTDIR=/tmp
          tree /tmp/usr
  debian:
    # Verify Debian package building
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          apt-get update
          apt-get install -y build-essential autoconf automake doxygen \
                             dpkg-dev debhelper devscripts
      - name: Configure
        run: |
          ./autogen.sh
          ./configure
      - name: Building Debian package
        run: |
          make package
